/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego_del_gato;


/**
 *
 * @author gary9
 */
public class Interfaz extends javax.swing.JFrame implements Runnable{
    
    public Interfaz() {
        initComponents();
        //Comando para pcentrar ventanay desabilitar maximizar
        setLocationRelativeTo(null);
        setResizable(false);
    }
    //Clase abstracta del metodo RUnnable
    @Override
    public void run() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        N1 = new javax.swing.JTextField();
        N2 = new javax.swing.JTextField();
        Emp_Jue = new javax.swing.JButton();
        Img_Mos = new javax.swing.JLabel();
        Emp_Nue = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        O = new javax.swing.JButton();
        X = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B1.setFont(new java.awt.Font("Segoe UI", 3, 100)); // NOI18N
        getContentPane().add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 120));

        B2.setFont(new java.awt.Font("Segoe UI", 3, 100)); // NOI18N
        getContentPane().add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 120, 120));

        B3.setFont(new java.awt.Font("Segoe UI", 3, 100)); // NOI18N
        getContentPane().add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 120, 120));

        B4.setFont(new java.awt.Font("Segoe UI", 3, 100)); // NOI18N
        getContentPane().add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, 120));

        B5.setFont(new java.awt.Font("Segoe UI", 3, 100)); // NOI18N
        getContentPane().add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 120, 120));

        B6.setFont(new java.awt.Font("Segoe UI", 3, 100)); // NOI18N
        getContentPane().add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 120, 120));

        B7.setFont(new java.awt.Font("Segoe UI", 3, 100)); // NOI18N
        getContentPane().add(B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 120, 120));

        B8.setFont(new java.awt.Font("Segoe UI", 3, 100)); // NOI18N
        getContentPane().add(B8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 120, 120));

        B9.setFont(new java.awt.Font("Segoe UI", 3, 100)); // NOI18N
        getContentPane().add(B9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 120, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/numeral.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setText("JUGADOR 2:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 150, -1));

        jLabel3.setText("JUGADOR 1:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 150, -1));

        N1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N1ActionPerformed(evt);
            }
        });
        getContentPane().add(N1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 140, -1));

        N2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N2ActionPerformed(evt);
            }
        });
        getContentPane().add(N2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 140, -1));

        Emp_Jue.setText("EMPEZAR JUEGO");
        getContentPane().add(Emp_Jue, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 140, -1));

        Img_Mos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Imagen_deco.png"))); // NOI18N
        getContentPane().add(Img_Mos, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 150, 230));

        Emp_Nue.setText("NUEVO JUEGO");
        getContentPane().add(Emp_Nue, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 140, -1));

        jLabel4.setText("JUGADOR 2:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 150, -1));

        O.setText("O");
        getContentPane().add(O, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 40, -1));

        X.setText("X");
        getContentPane().add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 40, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void N1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N1ActionPerformed
        N1.setEnabled(false);
    }//GEN-LAST:event_N1ActionPerformed

    private void N2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N2ActionPerformed
        N2.setEnabled(false);
    }//GEN-LAST:event_N2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton B1;
    public javax.swing.JButton B2;
    public javax.swing.JButton B3;
    public javax.swing.JButton B4;
    public javax.swing.JButton B5;
    public javax.swing.JButton B6;
    public javax.swing.JButton B7;
    public javax.swing.JButton B8;
    public javax.swing.JButton B9;
    public javax.swing.JButton Emp_Jue;
    public javax.swing.JButton Emp_Nue;
    private javax.swing.JLabel Img_Mos;
    public javax.swing.JTextField N1;
    public javax.swing.JTextField N2;
    public javax.swing.JButton O;
    public javax.swing.JButton X;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    //Llamada de eventos en clase controlador
    public void Controlador(Controlador event){
      
        B1.addActionListener(event);
        B1.setActionCommand("B1");
        
        B2.addActionListener(event);
        B2.setActionCommand("B2");
        
        B3.addActionListener(event);
        B3.setActionCommand("B3");
        
        B4.addActionListener(event);
        B4.setActionCommand("B4");
        
        B5.addActionListener(event);
        B5.setActionCommand("B5");
        
        B6.addActionListener(event);
        B6.setActionCommand("B6");
        
        B7.addActionListener(event);
        B7.setActionCommand("B7");
        
        B8.addActionListener(event);
        B8.setActionCommand("B8");
        
        B9.addActionListener(event);
        B9.setActionCommand("B9");
        
        Emp_Jue.addActionListener(event);
        Emp_Jue.setActionCommand("Comenzar");
        
        Emp_Nue.addActionListener(event);
        Emp_Nue.setActionCommand("JuegoNuevo");
        
        X.addActionListener(event);
        X.setActionCommand("X");
        
        O.addActionListener(event);
        O.setActionCommand("O");
        
        //Llamada de clase solo 
        N1.addKeyListener(new Mayusculas());
        N2.addKeyListener(new Mayusculas());
    }
    
}
